# Generated by Django 5.0.7 on 2024-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CI',
            fields=[
                ('project_id', models.CharField(max_length=200)),
                ('draw_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CIV',
            fields=[
                ('project_id', models.CharField(max_length=200)),
                ('draw_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='contractor',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EEE',
            fields=[
                ('project_id', models.CharField(max_length=200)),
                ('draw_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ME',
            fields=[
                ('project_id', models.CharField(max_length=200)),
                ('draw_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('project_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('project_Title', models.TextField(max_length=200)),
                ('dept', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=500)),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='verifier',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
